version: "3.9"
services:
  backend:
    environment:
      - PORT=${PORT}
      - RUST_LOG=${RUST_LOG}
      - KEY_PATH=${KEY_PATH}
      - CERT_PATH=${CERT_PATH}
    network_mode: "bridge"
    build: .
    shm_size: '1gb'
    ports:
      - "${PORT}:${PORT}"
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sess
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge

volumes:
  db:
