[package]
name = "context"
version = "0.1.0"
edition = "2021"

[dependencies]
juniper = "0.15.11"
once_cell = "1.17.1"
tokio = { version = "1.28.0", features = ["sync"]}
statistics = { path = "../statistics" }
migration = { path = "../migration" }
log = "0.4.19"
sea-orm = { version = "0.12.1" }
